nameOverride: simple-status

includes:
  ingress: true
  service: true
  deployment: true
  statefulset: false
  envSecret: false
  envConfigMap: false
  files: false
  configFiles: false
  binaryFiles: false
  pvcs: true
  job: false
  cronjob: false
  servicemonitor: false
  networkpolicy: false

secrets:
  data:
    registry:
      pullSecret:
        enabled: true
        name: harbor-registry-secret

ingresses:
  ingress:
    deploy: true
    ingressClassName: "kb-sh"
    tls:
      type: "existing"
      existing:
        secret: simple-status-tls

components:
  simplestatus:
    services:
      http:
        deploy: true
        port: 8080
        targetPort: 8080
    controller:
      deploy: true
      replicas: 1
      type: Deployment
      extraLabels:
        "customer.gitops.bedag.ch/hlq": "a99"
        "customer.gitops.bedag.ch/stage": "${stage}"
      containers:
        simplestatus:
          image:
            repository: artifacts.bedag.cloud/apc/simple-status
            tag: v0.0.7
          containerPorts:
            - name: http
              containerPort: 8080
          env:
            # - name: DB_CONN_STR
            #   value: "postgres://user:password@server:port/schema"
            # - name: S3_ENDPOINT
            #   value: "https://s3.ch:10443"
            # - name: AWS_ACCESS_KEY_ID
            #   value: "myaccesskey"
            # - name: AWS_SECRET_ACCESS_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: s3-secrets               # Secret muss entsprechend erstellt werden
            #       key: access-key
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          containerSecurityContext:
            enabled: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
