# sops enrypted secret values
components:
    geo-metadata-engine:
        controller:
            containers:
                geo-metadata-engine:
                    envSecret:
                        SECRET_KEY: ""
                        DB_HOST: ENC[AES256_GCM,data:S9E+IX+Qw4eBzk4zjwz3SfTqK8U329fSE+Qq,iv:ZkPmuF1pyCI5An6PtdorPKIEmTEQ/zdBK2OXUIqN9HQ=,tag:GTdRq2sMpFs3Nay9G6EOWQ==,type:str]
                        DB_PORT: ENC[AES256_GCM,data:DQ4W6YU=,iv:sOj9sSn5uLKKDwyZrQF37D2qEPTxRW7Ip2I+Bj6slGk=,tag:qUghkxS+IN553ti6QILEnA==,type:str]
                        DB_NAME: ENC[AES256_GCM,data:ABKXC2MiOEgzIA==,iv:gCy3fO/zsXCj15tyaCweZ7LbJtE1LwZvBeiSqgUq5Nc=,tag:WNs8buLkUj6+9P9iAx2O3w==,type:str]
                        DB_USER: ENC[AES256_GCM,data:SlGqyolPR1KJ,iv:G8+GgvSTjcl3aax+J2Px8vi7yE2F3kY81TomrN3ECT0=,tag:+LlqzabIoFEs9L3vF1DJig==,type:str]
                        DB_PASSWORD: ENC[AES256_GCM,data:jtEwEv+eul+cSfNyy1mq8Q+XleM=,iv:F67S/sVtpggigNRrjZMyWtBsKz2PW+g+Xua+00OXzAo=,tag:AJGM+dWrQsj1jjvlESCp5A==,type:str]
                        ADFS_SERVER: ENC[AES256_GCM,data:PZX5f5prQioLEMZ5/TuiyJQC,iv:95QVU9uH+ANopdQq3xWRD/y6R1kHN5DEnMZjNfbPmRA=,tag:s6t8iNrwWHW6j48HrDCjbA==,type:str]
                        ADFS_CLIENT_ID: ""
                        ADFS_RELYING_PARTY_ID: ""
                        ADFS_AUDIENCE: ""
sops:
    lastmodified: "2026-06-25T09:46:55Z"
    mac: ENC[AES256_GCM,data:b4H89mTC2mO1hiCgRjtsrt6uCp9hagtEe2/QH/o7ChhFn9buZ+2rcckpDzuh4TSA8yxolLeqs6v38ULW8lrkxp4SzT/bLgBCf/ysjm6DMiZNPVqNArQvnomkca5KCr1NANxnTGSDutLdnLaRU6X0wPYpZv/DMgzZz96T804HmuY=,iv:J8o+h0l69Np8zAgxFZoaIG/71RZg4Ii9AAmzuO9YPCY=,tag:Sz9AdcBX8I/kugXFI9Rv0g==,type:str]
    pgp:
        - created_at: "2026-06-17T10:49:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+XqmPYIdXJWAQ//fA2wfs1h51dXvrIev/uXu90QGxjcjJv+65+2GNTgnfYC
            s8wC9oSthUue7wOFX4LnblW+3egb/Cin9tu1HRwbzIKb2qPlRqcN0SHOSetITlfU
            TIHlksRsV1nGLGsmxw6Qm3l91nVqbV3GOFJlfxVC5KyYhHxsxJwrSWkaQXESqzxb
            JWDHMLa0qJuvlTOtH3EIif9Nz+qKOJ7z/ZzOhgX8FIoth7zF2uWKOxAsB/NgS2qq
            95D31LHdmeynFtxNLFxbSyFhrRQuat0C0CIDDSvy1dMl3vZaQFkTwWNVwbpXmpk0
            4mtY0fl+yIIs9afodIBSjuNxLmcbfwycik3TO1qiN7eyX198BecjxRfCbPSMTLtl
            EVpmjbqIPlxjC5KKzUCNT3a3iQgSAgffy9d7pMaD/Ajp/V/JLmtzlYniZ+HSWFpm
            Wg7sEeaFGHSOciyL4lV6j0WOyROK1U7KSp30HuCamTR1pOEdkj3LfgZb9oRceKhS
            z5YKXdOLtpqQ0DUpZK2Al6PixDks/rlkBKo1VBzLB60UeQFTxzmXwE41pnmqbNxB
            iTjTNG05Mz5JlCedcYNoQ0sXKdPXGmbDN/njt+pMXiE5dImtyk1wl7CYPa6h8gES
            xGO3BzOqt6EkwgCcXm89KcFHHRMDdlnAHUwJtb+dA3+Z2IhAQgTS1djloOOiYr3S
            XAE6a3AUwN54yjGdTkiufcSwxUNSjZS9wQ0yOC7xTR8zzMrPjgqzmwB95YnV0AP7
            A6jsLBaKSJULjjHOlz8YdaMhcse8yclKWl6nhh7O1daEAIaBBLPPRHQ84xAt
            =Hl9N
            -----END PGP MESSAGE-----
          fp: 48FE1781BD24F086AEDD4895E8EF50A1925535EB
    encrypted_regex: ^(.*)$
    version: 3.10.2
