# sops enrypted secret values
components:
    geo-metadata-engine:
        controller:
            containers:
                geo-metadata-engine:
                    envSecret:
                        SECRET_KEY: ENC[AES256_GCM,data:KX081tajAgsXT4QpNHoTZ4CyBj8b/Uhu4kSDBSUY/OG9oMX0FL5mYWgSrAiKsvlY8MHA5CezbuY0ymJvIgdH5D3z,iv:e1LFYUQynoUS23vdtvIkpurx7SDNQuLsdsZvexKtDsI=,tag:FOi14YyoK/EDUREde56Dyg==,type:str]
                        DB_HOST: ENC[AES256_GCM,data:S9E+IX+Qw4eBzk4zjwz3SfTqK8U329fSE+Qq,iv:ZkPmuF1pyCI5An6PtdorPKIEmTEQ/zdBK2OXUIqN9HQ=,tag:GTdRq2sMpFs3Nay9G6EOWQ==,type:str]
                        DB_PORT: ENC[AES256_GCM,data:DQ4W6YU=,iv:sOj9sSn5uLKKDwyZrQF37D2qEPTxRW7Ip2I+Bj6slGk=,tag:qUghkxS+IN553ti6QILEnA==,type:str]
                        DB_NAME: ENC[AES256_GCM,data:ABKXC2MiOEgzIA==,iv:gCy3fO/zsXCj15tyaCweZ7LbJtE1LwZvBeiSqgUq5Nc=,tag:WNs8buLkUj6+9P9iAx2O3w==,type:str]
                        DB_USER: ENC[AES256_GCM,data:SlGqyolPR1KJ,iv:G8+GgvSTjcl3aax+J2Px8vi7yE2F3kY81TomrN3ECT0=,tag:+LlqzabIoFEs9L3vF1DJig==,type:str]
                        DB_PASSWORD: ENC[AES256_GCM,data:jtEwEv+eul+cSfNyy1mq8Q+XleM=,iv:F67S/sVtpggigNRrjZMyWtBsKz2PW+g+Xua+00OXzAo=,tag:AJGM+dWrQsj1jjvlESCp5A==,type:str]
                        ADFS_SERVER: ENC[AES256_GCM,data:4lBvnRFctvMHvQ==,iv:UKxQBdkXo6kWHF4SfA0uiroYgVwJLMiFl8Mv1PUoZqA=,tag:i1Xdry/bvXdSWw33B7siJg==,type:str]
                        ADFS_CLIENT_ID: ENC[AES256_GCM,data:Tv9VTdgHAz280JdmwhxQbazXUJZoWqOZmiiWGGlNjXmlW8nF,iv:tm8LFbWs34MIQ8UvxwXaLdMI+c4UPJWXoy07exbFk8o=,tag:NmUW3FHaKL65gqSu4MQ2LA==,type:str]
                        ADFS_RELYING_PARTY_ID: ENC[AES256_GCM,data:Z/NrPo06KUq493mc2KqZERZq3Nnq3ykurUXuPDtJD+cB5VWK,iv:VPGUB83hACNMZZ30FW9/24pdLBdmLOb8sRDMPbzkriY=,tag:YhOlnDz45MTxhHYdYeHKMg==,type:str]
                        ADFS_AUDIENCE: ENC[AES256_GCM,data:vQdmPuz36ohzMj/gt0acFDAM9X7rNc5k/xdlWJIP9oJubnAxpxiAEFHSSc2kVC4Jn3RSH/fv0144aND+EQ==,iv:LcZXlnJ3VXtdU+9JyHDbf4jbUXTM0vDeGqcA7fzhv3k=,tag:w27mE+cIJQuUFtz3+1n5jg==,type:str]
                        ADFS_CLIENT_SECRET: ENC[AES256_GCM,data:NPEWe93O6YfY/se9Cn1zTTqNAKVoTWnjhheDJ2AHHGgB8I4fgEaWXw==,iv:r4h8kxNrIcEbQ/FKBtx24W9mNQKqN7VMDw/q2ZMCDQI=,tag:UOkfK2+rtKwoyF51CZRDkA==,type:str]
sops:
    lastmodified: "2026-07-02T15:26:25Z"
    mac: ENC[AES256_GCM,data:fWT4KH4EjVszpw7H4eiBnoUpU0X9b2x+yzc9H42KwjI9tr7VA1IGDzCxjGo8JIe93zormDR2I/4XWZ3Spys8g6LXfIZOyORr8INXc/LA2mzFkRstv9vIbe2nKOLRY3CeXxGs/L3H69RjHaTNCTIVnLY+2gRJqNLANKU6ABsWbe8=,iv:zqZ+HDVTZxLuVPMppZ9aHb/KU++mRPKN8pTUFLFNN3g=,tag:jUAcbg53dxaV1Scse7dy6Q==,type:str]
    pgp:
        - created_at: "2026-06-17T10:49:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+XqmPYIdXJWAQ//fA2wfs1h51dXvrIev/uXu90QGxjcjJv+65+2GNTgnfYC
            s8wC9oSthUue7wOFX4LnblW+3egb/Cin9tu1HRwbzIKb2qPlRqcN0SHOSetITlfU
            TIHlksRsV1nGLGsmxw6Qm3l91nVqbV3GOFJlfxVC5KyYhHxsxJwrSWkaQXESqzxb
            JWDHMLa0qJuvlTOtH3EIif9Nz+qKOJ7z/ZzOhgX8FIoth7zF2uWKOxAsB/NgS2qq
            95D31LHdmeynFtxNLFxbSyFhrRQuat0C0CIDDSvy1dMl3vZaQFkTwWNVwbpXmpk0
            4mtY0fl+yIIs9afodIBSjuNxLmcbfwycik3TO1qiN7eyX198BecjxRfCbPSMTLtl
            EVpmjbqIPlxjC5KKzUCNT3a3iQgSAgffy9d7pMaD/Ajp/V/JLmtzlYniZ+HSWFpm
            Wg7sEeaFGHSOciyL4lV6j0WOyROK1U7KSp30HuCamTR1pOEdkj3LfgZb9oRceKhS
            z5YKXdOLtpqQ0DUpZK2Al6PixDks/rlkBKo1VBzLB60UeQFTxzmXwE41pnmqbNxB
            iTjTNG05Mz5JlCedcYNoQ0sXKdPXGmbDN/njt+pMXiE5dImtyk1wl7CYPa6h8gES
            xGO3BzOqt6EkwgCcXm89KcFHHRMDdlnAHUwJtb+dA3+Z2IhAQgTS1djloOOiYr3S
            XAE6a3AUwN54yjGdTkiufcSwxUNSjZS9wQ0yOC7xTR8zzMrPjgqzmwB95YnV0AP7
            A6jsLBaKSJULjjHOlz8YdaMhcse8yclKWl6nhh7O1daEAIaBBLPPRHQ84xAt
            =Hl9N
            -----END PGP MESSAGE-----
          fp: 48FE1781BD24F086AEDD4895E8EF50A1925535EB
    encrypted_regex: ^(.*)$
    version: 3.10.2
