# Generated by Django 6.0.3 on 2026-05-12 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0019_remove_layergroup_layer_delete_webmap_delete_layer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('email_kontakt', models.EmailField(max_length=254)),
                ('email_user', models.EmailField(max_length=254)),
                ('abteilung', models.CharField(choices=[('AFR', 'AFR'), ('WAA', 'WAA'), ('WAV', 'WAV'), ('WAM', 'WAM'), ('WABJ', 'WABJ'), ('AWE', 'AWE'), ('SFB', 'SFB'), ('NGA', 'NGA')], max_length=10)),
                ('funktion', models.CharField(blank=True, choices=[('Hauptförster', 'Hauptförster'), ('Nebenförster', 'Nebenförster'), ('Käfervogt', 'Käfervogt'), ('Kontroller', 'Kontroller')], max_length=20)),
                ('eintritt_am', models.DateField()),
                ('status', models.CharField(choices=[('zu bestellen', 'Zu bestellen'), ('bestellt', 'Bestellt'), ('aktiv', 'Aktiv'), ('zu löschen', 'Zu löschen'), ('inaktiv', 'Inaktiv')], max_length=20)),
                ('usertyp', models.CharField(choices=[('intern', 'Intern'), ('extern', 'Extern')], max_length=10)),
                ('rolle', models.CharField(choices=[('Viewer', 'Viewer'), ('Editor', 'Editor'), ('Creator', 'Creator')], max_length=10)),
                ('racf_id', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('typ_account', models.CharField(choices=[('AD', 'AD'), ('BE-Login', 'BE-Login'), ('Built-In', 'Built-In')], max_length=20)),
                ('typ_infomail', models.CharField(choices=[('Störung', 'Störung'), ('Erweiterung/Störung', 'Erweiterung/Störung')], max_length=30)),
                ('ews', models.BooleanField(default=False)),
                ('bkt', models.BooleanField(default=False)),
                ('prod', models.BooleanField(default=False)),
                ('status_nb', models.CharField(blank=True, max_length=100)),
                ('nb_pdf', models.FileField(blank=True, null=True, upload_to='nb_pdfs/')),
                ('bemerkung', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Portal User',
                'verbose_name_plural': 'Portal Users',
                'ordering': ['name'],
            },
        ),
    ]
