# Generated by Django 6.0.3 on 2026-05-13 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0020_portaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='benutzertyp',
            field=models.CharField(default='Creator', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='bkt',
            field=models.BooleanField(default=False, verbose_name='BKT'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='ews',
            field=models.BooleanField(default=False, verbose_name='EWS'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='prod',
            field=models.BooleanField(default=False, verbose_name='PROD'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='racf_id',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='RACF-ID'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='rolle',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('Dateneditor', 'Dateneditor'), ('Publisher', 'Publisher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='status',
            field=models.CharField(choices=[('zu bestellen', 'zu bestellen'), ('bestellt', 'bestellt'), ('aktiv', 'aktiv'), ('zu löschen', 'zu löschen'), ('inaktiv', 'inaktiv')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='usertyp',
            field=models.CharField(choices=[('intern', 'intern'), ('extern', 'extern')], max_length=10),
        ),
    ]
