# Generated by Django 6.0.3 on 2026-05-13 06:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0021_add_benutzertyp_to_portal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='nb_pdf',
            field=models.FileField(blank=True, null=True, upload_to='nb_pdfs/', verbose_name='Nutzungsbedingungen PDF'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='status_nb',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status Nutzungsbedingungen'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='typ_account',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AD', 'AD'), ('BE-Login', 'BE-Login'), ('Built-In', 'Built-In')], max_length=20), blank=True, default=list),
        ),
    ]
