# Generated by Django 6.0.3 on 2026-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0022_typ_account_array_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='usertyp',
        ),
        migrations.AddField(
            model_name='portaluser',
            name='intern',
            field=models.BooleanField(default=True, verbose_name='Intern'),
        ),
    ]
