# Generated by Django 6.0.3 on 2026-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0023_replace_usertyp_with_intern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='typ_infomail',
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='funktion',
            field=models.CharField(choices=[('andere', 'andere (siehe Bemerkung)'), ('Hauptförster', 'Hauptförster'), ('Nebenförster', 'Nebenförster'), ('Käfervogt', 'Käfervogt'), ('Kontroller', 'Kontroller')], default='andere', max_length=20),
        ),
    ]
