# Generated by Django 6.0.3 on 2026-05-20 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0024_remove_typ_infomail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='id',
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='racf_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='RACF-ID'),
        ),
    ]
