# Generated by Django 4.2 on 2026-05-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0025_racf_id_primary_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="view",
            name="dienst",
        ),
        migrations.AddField(
            model_name="view",
            name="dienste",
            field=models.ManyToManyField(
                blank=True, related_name="views", to="editor.dienst"
            ),
        ),
    ]
