# Generated by Django 6.0.6 on 2026-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0028_portaluser_field_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='status_nb',
            field=models.CharField(blank=True, max_length=200, verbose_name='Status Nutzungsbedingungen'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='vorname',
            field=models.CharField(max_length=200),
        ),
    ]
