# Generated by Django 6.0.6 on 2026-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0029_alter_portaluser_id_alter_portaluser_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='portaluser',
            constraint=models.UniqueConstraint(condition=models.Q(('racf_id__isnull', False)), fields=('racf_id',), name='unique_racf_id_when_not_null'),
        ),
    ]
