# Generated by Django 6.0.6 on 2026-06-08 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0030_unique_racf_id_when_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='racf_id',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='RACF-ID'),
        ),
    ]
