apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: geo-metadata-engine
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: geo-metadata-engine-geo-metadata-engine
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/readinessProbe
                value:
                  httpGet:
                    path: /readiness/
                    port: 8000
                    httpHeaders:
                      - name: Host
                        value: geo-metadata-engine.apps.be.ch
              - op: add
                path: /spec/template/spec/containers/0/livenessProbe
                value:
                  httpGet:
                    path: /liveness/
                    port: 8000
                    httpHeaders:
                      - name: Host
                        value: geo-metadata-engine.apps.be.ch